#!/usr/bin/env python3
"""Publish the checkpoints and datasets a reader needs to reproduce the paper.

Sidecar, like `wandb_log.py`: nothing in `latent_noether/` or `scripts/` imports this, and it never
writes into `runs/`. The raw rows stay immutable.

**Private by default.** The manuscript is unpublished. Making a repo public is not meaningfully
reversible -- once a checkpoint is fetched it is out -- so `--public` must be passed explicitly.

`runs/` holds 6.2 GB, most of it intermediate checkpoint ladders that exist to support the E8
training-saturation sweep. Uploading all of it would bury the artifacts that matter. The selection
below is exactly the set that backs a claim in `paper1.2`, and each entry records which.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RUNS = ROOT / "runs"

# path glob -> what it backs. Anything not listed here is deliberately not uploaded.
SELECTION: list[tuple[str, str]] = [
    ("dreamer_ref_s[345]_step6500.pt",
     "Primary analysis checkpoints. E1 repair, E4 dialing, E9 disjoint eval, E12c interchange, "
     "E18 supervised probe, E19 shadow Hamiltonian."),
    ("dreamer_ref_s[345]_step60000.pt", "E8 training-saturation arm: the repair persists at convergence."),
    ("dreamer_damped_s[012].pt", "Dissipative control (arm C): the method refuses on a damped system."),
    ("osc2d_nc_s[345].pt", "E17, two degrees of freedom, non-central arm."),
    ("osc2d_ce_s[02].pt", "E17/E10b central arm (two-invariant degeneracy)."),
    ("gru_ref_s[345].pt", "F4, second architecture (conv-GRU)."),
    ("gru56_ref_s[345].pt", "F4b, conv-GRU with 7x more open-loop training."),
    ("f1_act_s[345].pt", "F1/F5, action-conditioned models."),
    ("f6_dt*_s[345]_step6500.pt",
     "F6, the timestep-scaling result: four simulator timesteps x three seeds. The models that "
     "recover c* = (dt/2) mg(l/2) across a 4x range of dt."),
    ("*.npz", "All datasets, including the four F6 timestep variants. Every result is reproducible "
     "from these plus the checkpoints above."),
    ("pixel_readout_calibration.json", "The frozen pixel-readout pivot; the decoded-energy metric depends on it."),
]


def gather() -> list[tuple[pathlib.Path, str]]:
    out, seen = [], set()
    for pat, why in SELECTION:
        for p in sorted(RUNS.glob(pat)):
            if p.name not in seen:
                seen.add(p.name); out.append((p, why))
    return out


def sha256(p: pathlib.Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for c in iter(lambda: f.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


def build_manifest(files: list[tuple[pathlib.Path, str]]) -> str:
    rows = ["# Artifact manifest", "",
            "Generated by `tools/hf_upload.py`. Each file is listed with the claim it backs and its",
            "sha256, so a download can be checked against the record the experiments were run on.", ""]
    rows += ["| file | MB | sha256 (first 16) | backs |", "|---|---|---|---|"]
    for p, why in files:
        rows.append(f"| `{p.name}` | {p.stat().st_size/1e6:.1f} | `{sha256(p)[:16]}` | {why} |")
    return "\n".join(rows) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default="Zarand3r/world-model-invariants")
    ap.add_argument("--public", action="store_true",
                    help="create the repo PUBLIC. Off by default: the manuscript is unpublished "
                         "and publishing a checkpoint is not reversible.")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    files = gather()
    total = sum(p.stat().st_size for p, _ in files) / 1e6
    print(f"  {len(files)} files, {total:.0f} MB -> {a.repo} ({'PUBLIC' if a.public else 'private'})")
    if a.dry_run:
        for p, _ in files:
            print(f"    {p.name:38s} {p.stat().st_size/1e6:7.1f} MB")
        return 0

    from huggingface_hub import HfApi
    api = HfApi()
    try:                              # fail fast, before any upload begins
        api.whoami()
    except Exception as e:
        print(f"hf auth failed: {type(e).__name__}: {e}", file=sys.stderr)
        return 1

    # create_repo(exist_ok=True) does NOT change the visibility of a repo that already exists, so
    # it will silently return a PUBLIC repo while the caller believes it asked for a private one.
    # That happened on 2026-08-29: this tool reported "private" and uploaded into a public repo
    # created two days earlier. Check the real visibility and refuse rather than assume.
    api.create_repo(a.repo, repo_type="model", private=not a.public, exist_ok=True)
    actual_private = api.repo_info(a.repo, repo_type="model").private
    if actual_private == a.public:          # visibility disagrees with what was asked for
        state = "PUBLIC" if not actual_private else "private"
        want = "public" if a.public else "private"
        if not a.public:
            print(f"refusing: {a.repo} already exists and is {state}, but --public was not passed.\n"
                  f"          Pass --public to upload into it knowingly, or make it {want} first.",
                  file=sys.stderr)
            return 1
        print(f"  note: repo already existed as {state}", file=sys.stderr)
    man = ROOT / "docs" / "ARTIFACT_MANIFEST.md"
    man.write_text(build_manifest(files))
    api.upload_file(path_or_fileobj=str(man), path_in_repo="MANIFEST.md",
                    repo_id=a.repo, repo_type="model")
    for p, _ in files:
        sub = "data" if p.suffix == ".npz" else ("meta" if p.suffix == ".json" else "checkpoints")
        api.upload_file(path_or_fileobj=str(p), path_in_repo=f"{sub}/{p.name}",
                        repo_id=a.repo, repo_type="model")
        print(f"    uploaded {sub}/{p.name}", flush=True)
    print(f"  done -> https://huggingface.co/{a.repo}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
